language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
cache:
  - $HOME/.pip-cache
# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements-travis.txt --download-cache $HOME/.pip-cache
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi  # needs for running tests
# command to run tests
script: nosetests
notifications:
  email:
    - abhishek.lekshmanan@gmail.com
